# Site settings
title: 余朝歌
header-img: "img/Xacebook.jpg"
tagline: "cn"  
description: "余朝歌"  
baseurl: ""
url: "http://yuzhaoge.com"  

# About/contact
owner: 
  name: " yuzhaoge"
  email: yuchaoafei@aliyun.com
  bio: "yuzhaoge"

# Data
gavatar: http://openmindclub.qiniudn.com/omt/favicon.png
favicon: img/favicon.ico

douban_username:  yuzhaoge
twitter_username: yuzhaoge
github_username: yuzhaoge
facebook_username: yuzhaoge
weibo_username: yuzhaoge 
zhihu_username: yuzhaoge

# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 15
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai

# Defaults for posts
defaults:
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "yuzhaoge"
      header-img: "img/green.jpg" # We don't want posts without a header image, that whould mean white on white

# Comments 
comments :
  provider : disqus
  duoshuo :
    short_name : yuzhaoge
  disqus :
      short_name : yuzhaoge

# Analytics and webmaster tools stuff goes here
google_analytics: UA-80884545-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation